 version: "3"
 services:
   web:
     # 将 username/repo:tag 替换为您的名称和镜像详细信息
     image: testnum1:latest
     deploy:
       replicas: 2
       restart_policy:
         condition: on-failure
       resources:
         limits:
           cpus: "0.8"
           memory: 500M
     ports:
       - "80:8000"
     networks:
       - webnet
   visualizer:
     image: dockersamples/visualizer:stable
     ports:
       - "8080:8080"
     volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
     deploy:  
       placement:
         constraints: [node.role == manager]
     networks:
       - webnet
   cassandra:
     image: cassandra
     ports:
       - "9042:9042"
     volumes:
       - ./data:/data
     deploy:
       placement:
         constraints: [node.role == manager]
     networks:
       - webnet
 networks:
   webnet:

